### ISSUE TITLE
git clone --recursive error: No submodule mapping found in .gitmodules for path 'go/src/code.google.com/p/biogo.bam'

### ISSUE THREAD

**Issue by lifengtian** [10XGenomics/lariat#1]
$ git clone --recursive https://github.com/10XGenomics/lariat.git
Cloning into 'lariat'...
remote: Counting objects: 59, done.
remote: Total 59 (delta 0), reused 0 (delta 0), pack-reused 59
Unpacking objects: 100% (59/59), done.
Checking connectivity... done.
No submodule mapping found in .gitmodules for path 'go/src/code.google.com/p/biogo.bam'

**Comment by wheaton5** [comment]
This works for multiple people here. Could this be a git version issue? I understand that the name of the submodule path and the url are different but as long as the mapping is in the .gitmodules that should be fine.

**Comment by wangyugui** [comment]
This happened on CentOS 7.2 & git 2.7.4

```[root@T630 fixed]# git clone --recursive https://github.com/10XGenomics/lariat.git
Cloning into 'lariat'...
remote: Counting objects: 65, done.
remote: Total 65 (delta 0), reused 0 (delta 0), pack-reused 65
Unpacking objects: 100% (65/65), done.
Checking connectivity... done.
Submodule 'go/src/code.google.com/p/biogo.bam' (git@github.com:10XGenomics/hts.git) registered for path 'go/src/code.google.com/p/biogo.bam'
Submodule 'go/src/github.com/davecheney/profile' (git@github.com:davecheney/profile.git) registered for path 'go/src/github.com/davecheney/profile'
Submodule 'go/src/gobwa/bwa' (https://github.com/lh3/bwa.git) registered for path 'go/src/gobwa/bwa'
Cloning into 'go/src/code.google.com/p/biogo.bam'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:10XGenomics/hts.git' into submodule path 'go/src/code.google.com/p/biogo.bam' failed
[root@T630 fixed]# git --version
git version 2.7.4

```
```

**Comment by pmarks** [comment]
Issue should be resolved now.  If you don't have SSH keys setup to a github account, then fetching submodules with the ssh urls from .gitmodules will not work.  I've updated those URLs to https, which will work for anonymous users.
