### ISSUE TITLE
Can't clone non-public submodule `biogo.bam`

### ISSUE THREAD

**Issue by zamaudio** [10XGenomics/lariat#16]
The submodule link for this repo is not publically accessible, is this intentional?

https://github.com/10XDev/biogo.bam

I'm not sure how anyone else is posting issues related to this project given it is currently impossible to build from source.  Can this be resolved please?

**Comment by zamaudio** [comment]
Not to mention, if Lariat is GPLv3 and you distribute it, you must provide all source code or you're breaking the license agreement.

**Comment by zamaudio** [comment]
OK so you relicensed the project to MIT by pointing your source code submodule for BWA to the Apache2 version.  Can I still get source code for biogo.bam?  I would like to compile Lariat from source...

**Comment by adam-azarchs** [comment]
I expect we'll get to this, but it might have to wait until relevant people get back from AGBT next week.  In the mean time, as best I can tell it's a fork off of [this commit](https://github.com/biogo/hts/tree/502217914e8710df24946caed03a7f576c9adff4) from biogo/hts with some bug fixes and performance enhancements.  At a glance there don't appear to be any breaking API changes.  I'd suggest we upstream those changes, but the upstream has diverged significantly since the fork so I have doubts as to whether that would be practical for us.

**Comment by olavurmortensen** [comment]
Is anyone going to fix this? Can't `10XDev/biogo.bam` just be made publlic, since this software is supposed to be open source?

**Comment by olavurmortensen** [comment]
@adam-azarchs @pmarks

**Comment by zamaudio** [comment]
@olavurmortensen I found a version of the submodule that seems to work and forked it here https://github.com/zamaudio/hts .  Lariat compiles with that, but not sure if its totally in sync with 10XDev version as I can't see it.

**Comment by adam-azarchs** [comment]
As previously noted, that 10X fork is off of https://github.com/biogo/hts/tree/502217914e8710df24946caed03a7f576c9adff4.  The only change I see relative to that are performance tweaks.  I'll try to find someone from that team with the bandwidth to fix this issue.

**Comment by olavurmortensen** [comment]
Awesome! Thank you so much for solving this. I ran the commands below with `go version go1.12.2 linux/amd64`, and it seems to work.

```
git clone --recursive https://github.com/10XGenomics/lariat.git
cd lariat/go/
make
./bin/lariat -h
```

**Comment by zamaudio** [comment]
@olavurmortensen FYI I think it was a stopgap measure by pointing to the old hts.  Would still be good to get the perf tweaks... the `10x` (lowercase x) branch here https://github.com/10XGenomics/hts/tree/10x seems more up to date than the master branch of hts.

**Comment by adam-azarchs** [comment]
Looks like https://github.com/10XGenomics/hts/commit/f064af33ec3c5cde12646e982998818ea5e78a04 was what longranger 2.2.2 shipped with.  I don't think any of the stuff more recent than that in the 10x branch has actually gone through a proper testing cycle.
