### ISSUE TITLE
MIT licence incompatible with linked library BWA

### ISSUE THREAD

**Issue by zamaudio** [10XGenomics/lariat#17]
You can't make this project licenced under MIT if it links to BWA at the object level.  BWA is GPLv3.

Please fix the licence text to correspond to the README that states that this project is licensed under GPLv3.  The license text for GPLv3 can be found here: http://www.gnu.org/licenses/gpl-3.0.txt

**Comment by pmarks** [comment]
Hi @zamaudio, thanks for the note.  We previously released lariat under the AGPL, but relicensed it to MIT recently.  I've updated our BWA submodule to the `Apache2` branch, which is Apache2 licensed, and fixed the note about the licensing situation in the README.

See #18 for details.
