### ISSUE TITLE
src/inference/bamwriter.go:8:2: no buildable Go source files in ~/src/lariat/go/src/gobwa

### ISSUE THREAD

**Issue by sjackman** [10XGenomics/lariat#8]
Steps to reproduce
```sh
git clone --recursive https://github.com/10XGenomics/lariat.git
make -C lariat/go
```

Log
```
make -C src/gobwa/bwa libbwa.a
make[1]: Entering directory '/home/sjackman/src/lariat/go/src/gobwa/bwa'
gcc -c -g -Wall -Wno-unused-function -O2 -DHAVE_PTHREAD -DUSE_MALLOC_WRAPPERS  utils.c -o utils.o
…
gcc -c -g -Wall -Wno-unused-function -O2 -DHAVE_PTHREAD -DUSE_MALLOC_WRAPPERS  malloc_wrap.c -o malloc_wrap.o
ar -csru libbwa.a utils.o kthread.o kstring.o ksw.o bwt.o bntseq.o bwa.o bwamem.o bwamem_pair.o bwamem_extra.o malloc_wrap.o
make[1]: Leaving directory '/home/sjackman/src/lariat/go/src/gobwa/bwa'
go install -ldflags "-X inference.__VERSION__ '29a7f74'" lariat
src/inference/bamwriter.go:8:2: no buildable Go source files in /home/sjackman/src/lariat/go/src/gobwa
make: *** [Makefile:9: lariat] Error 1
```

**Comment by wheaton5** [comment]
This does not reproduce for me. Will think about what possible causes are.

**Comment by sjackman** [comment]
If it's helpful for troubleshooting:
```
❯❯❯ git rev-parse origin/master
29a7f7406235839c2cb3e19bb1cf1ee17e3d0c7e
❯❯❯ go version
go version go1.8 linux/amd64
```

**Comment by wheaton5** [comment]
I have 
go version go1.3.1 linux/amd64
Not sure if this is the cause. I don't have access to change my go version. Will discuss with some ppl here who are more likely to know what could cause this. If you can, you might try go 1.3. There was a reason that we didn't update to go 1.5 that I don't remember at the moment.

**Comment by sjackman** [comment]
I was able to compile it successfully on macOS with the same version of Go (with a minor patch needed that I'll submit as a PR), so there's something funny about my Linux installation of Go.

**Comment by sjackman** [comment]
It is something funny with my Go installation on Linux. `cgo` is disabled. 😢
Not a terribly helpful error message from `Go` though: `no buildable Go source files`

**Comment by sjackman** [comment]
Once I recompiled `go` with support for `cgo` it works now! :tada:
